---
platform: darwin
inputs:
  - name: git-repo-rmock

outputs:
  - name: output

run:
  path: sh
  args:
    - -exc
    - |
      cd git-repo-rmock
      make pkg
      cd ..
      cp -R git-roku-radio-com-repo/dist/packages/ output/
