resources:
  - name: git-roku-radio-com-repo
    type: git
    source:
      branch: develop
      private_key: ((github-private-key))
      uri: git@github.com:Entercom/radio-roku.git
  - name: roku-radio-com-s3-zip
    type: s3
    source:
      bucket: roku-radio-com
      access_key_id: ((s3-access-key))
      region_name: ((s3-region))
      secret_access_key: ((s3-secret-key))
      regexp: roku_radio_com_(.*).zip
  - name: roku-radio-com-s3-pkg
    type: s3
    source:
      bucket: roku-radio-com
      access_key_id: ((s3-access-key))
      region_name: ((s3-region))
      secret_access_key: ((s3-secret-key))
      regexp: roku_radio_com_(.*).pkg

jobs:
  - name: package-roku-radio-com-app
    plan:
      - get: git-roku-radio-com-repo
      - task: package
        file: git-roku-radio-com-repo/ci/package.yml
        params:
          ROKU_DEV_TARGET: ((roku-dev-device-ip))
          DEVPASSWORD: ((roku-dev-password))
          APP_KEY_PASS: ((roku-app-key))
      - put: roku-radio-com-s3-pkg
        params:
          file: output/roku_radio_com_*.pkg

  - name: deploy-roku-radio-com-apps
    plan:
      - get: git-roku-radio-com-repo
        trigger: true
      - task: deploy
        file: git-roku-radio-com-repo/ci/deploy.yml
        params:
          ROKU_DEV_TARGET: ((roku-dev-device-ip))
          DEVPASSWORD: ((roku-dev-password))
          APP_KEY_PASS: ((roku-app-key))
      - put: roku-radio-com-s3-zip
        params:
          file: output/roku_radio_com_*.zip
